/**
 * The ground's and road's world-space detail tile.
 *
 * The surfaces these two materials draw were the audit's largest recorded appearance
 * gap: no map at all, a ±3% sinusoid at about 20 m on the ground, and a road grain
 * that faded out above 0.015–0.08 m/px. These cases hold the three properties the
 * replacement has to have to be worth anything:
 *
 * - **deterministic**, because the visual gate compares frames across runs and a tile
 *   that reshuffled itself would make the gate measure the shuffle. Same kind, same
 *   bytes, every call;
 * - **structured at more than one scale**, because a tile of pure fine grain mips to
 *   flat grey at the overhead framing, which is the defect it exists to fix;
 * - **selected at a scale the far frames can still resolve**, checked against the
 *   camera's own metres per pixel rather than asserted.
 *
 * **The bound.** These are properties of the generated bytes and of the chosen tile
 * size. They say nothing about how the tinted, lit, tone-mapped result looks: that is
 * the frame set's evidence, and no assertion here can stand in for it.
 */
import { describe, expect, it } from "vitest";

import {
  createSurfaceDetailTexture,
  DETAIL_SIZE,
  surfaceDetailBytes,
  SURFACE_DETAIL_METRES,
  SURFACE_DETAIL_STRENGTH,
  type SurfaceDetailKind,
} from "../src/scene/surface-detail.js";

const KINDS: readonly SurfaceDetailKind[] = ["ground", "road"];

/** Mean absolute difference between neighbouring texels, in 0-255 units. */
function adjacentDelta(texels: Uint8Array, step: number): number {
  let total = 0;
  let count = 0;
  for (let y = 0; y < DETAIL_SIZE; y += 1) {
    for (let x = 0; x < DETAIL_SIZE; x += 1) {
      const here = texels[(y * DETAIL_SIZE + x) * 4]!;
      const next = texels[(y * DETAIL_SIZE + ((x + step) % DETAIL_SIZE)) * 4]!;
      total += Math.abs(here - next);
      count += 1;
    }
  }
  return total / count;
}

describe("the surface detail tile is deterministic", () => {
  it("gives the same bytes for the same kind, every time", () => {
    for (const kind of KINDS) {
      const first = surfaceDetailBytes(kind);
      const second = surfaceDetailBytes(kind);
      expect(second.length).toBe(first.length);
      expect(Buffer.from(second).equals(Buffer.from(first))).toBe(true);
    }
  });

  it("gives the two surfaces different patterns", () => {
    const ground = surfaceDetailBytes("ground");
    const road = surfaceDetailBytes("road");
    expect(Buffer.from(road).equals(Buffer.from(ground))).toBe(false);
  });

  it("is opaque grey, one value per texel", () => {
    const texels = surfaceDetailBytes("ground");
    expect(texels.length).toBe(DETAIL_SIZE * DETAIL_SIZE * 4);
    for (let index = 0; index < texels.length; index += 4) {
      expect(texels[index]).toBe(texels[index + 1]);
      expect(texels[index]).toBe(texels[index + 2]);
      expect(texels[index + 3]).toBe(255);
    }
  });
});

describe("the tile carries structure at more than one scale", () => {
  it("is centred on the multiplier's neutral value", () => {
    for (const kind of KINDS) {
      const texels = surfaceDetailBytes(kind);
      let total = 0;
      let count = 0;
      for (let index = 0; index < texels.length; index += 4) {
        total += texels[index]!;
        count += 1;
      }
      // The shader reads `1 + (value/255 - 0.5) * strength`, so a mean away from the
      // midpoint would tint the surface rather than texture it. The generator centres
      // and scales the octave sum for exactly this, so the bound is tight.
      expect(Math.abs(total / count - 127.5)).toBeLessThan(1);
    }
  });

  it("has coarse variation, so minification does not converge it to flat", () => {
    for (const kind of KINDS) {
      const texels = surfaceDetailBytes(kind);
      // Mean of each 16x16 block: if the coarse octaves were missing, every block
      // would sit at the same value and this spread would collapse.
      const blocks: number[] = [];
      for (let by = 0; by < DETAIL_SIZE; by += 16) {
        for (let bx = 0; bx < DETAIL_SIZE; bx += 16) {
          let total = 0;
          for (let y = by; y < by + 16; y += 1) for (let x = bx; x < bx + 16; x += 1) total += texels[(y * DETAIL_SIZE + x) * 4]!;
          blocks.push(total / 256);
        }
      }
      const spread = Math.max(...blocks) - Math.min(...blocks);
      expect(spread, `${kind}: 16x16 block means span only ${spread.toFixed(1)} of 255`).toBeGreaterThan(20);
    }
  });

  it("wraps without a seam, so the tiling is not visible as a grid", () => {
    for (const kind of KINDS) {
      const texels = surfaceDetailBytes(kind);
      // The tile is periodic by construction, so the step across the wrap should look
      // like any other neighbouring step. A lattice that did not wrap would make this
      // roughly the difference between two unrelated texels instead.
      const interior = adjacentDelta(texels, 1);
      const wrap = adjacentDelta(texels, DETAIL_SIZE - 1);
      expect(wrap, `${kind}: wrap step ${wrap.toFixed(2)} against interior ${interior.toFixed(2)}`).toBeLessThan(interior * 2.5);
    }
  });
});

describe("the tile is chosen at a scale the far frames resolve", () => {
  it("spans several pixels at the overhead sweep's 1.374 m per pixel", () => {
    // 55 degrees vertical at 1280x720: the ground plane covers 2*d*tan(27.5) metres
    // vertically, so 1.374 m per pixel at the overhead shot's 950 m. A tile smaller
    // than a couple of pixels is minified to flat, which is the defect.
    const OVERHEAD_METRES_PER_PIXEL = (2 * 950 * Math.tan((27.5 * Math.PI) / 180)) / 720;
    expect(OVERHEAD_METRES_PER_PIXEL).toBeCloseTo(1.374, 2);
    for (const kind of KINDS) {
      expect(SURFACE_DETAIL_METRES[kind] / OVERHEAD_METRES_PER_PIXEL).toBeGreaterThan(2);
    }
    // And the road is the finer of the two, so the two surfaces are not the same
    // pattern at the same scale.
    expect(SURFACE_DETAIL_METRES.road).toBeLessThan(SURFACE_DETAIL_METRES.ground);
  });

  it("modulates the surface colour without swinging it into mud or blow-out", () => {
    for (const kind of KINDS) {
      expect(SURFACE_DETAIL_STRENGTH[kind]).toBeGreaterThan(0.05);
      expect(SURFACE_DETAIL_STRENGTH[kind]).toBeLessThan(0.35);
    }
  });
});

describe("the texture is set up for world-space tiling", () => {
  it("repeats, and generates mipmaps for the distance fade", () => {
    for (const kind of KINDS) {
      const texture = createSurfaceDetailTexture(kind);
      // Repeat wrapping is what makes a world-space coordinate a tile UV, and the mip
      // chain is the whole distance fade: `DataTexture` arrives with mipmaps off and
      // nearest filtering, so both are set explicitly and asserted here.
      expect(texture.wrapS).toBe(1000);
      expect(texture.wrapT).toBe(1000);
      expect(texture.generateMipmaps).toBe(true);
      expect(texture.image.width).toBe(DETAIL_SIZE);
      expect(texture.image.height).toBe(DETAIL_SIZE);
      texture.dispose();
    }
  });
});
