/**
 * The ground's and road's world-space detail tile.
 *
 * The surfaces these two materials draw were the audit's largest recorded appearance
 * gap: no map at all, a ±3% sinusoid at about 20 m on the ground, and a road grain
 * that faded out above 0.015–0.08 m/px. These cases hold the three properties the
 * replacement has to have to be worth anything:
 *
 * - **deterministic**, because the visual gate compares frames across runs and a tile
 *   that reshuffled itself would make the gate measure the shuffle. Same kind, same
 *   bytes, every call;
 * - **structured at more than one scale**, because a tile of pure fine grain mips to
 *   flat grey at the overhead framing, which is the defect it exists to fix;
 * - **visible, not merely present.** The first version satisfied the two above and was
 *   measured invisible in the frames: 0.36% of albedo between neighbouring texels on the
 *   road, 0.1 of a display level. The step in albedo (the tile's step times the
 *   strength the shader applies) is now asserted at both the magnified and the minified
 *   ends of the hero crossing's 0.0144-0.0886 m/px;
 * - **selected at a scale the far frames can still resolve**, checked against the
 *   camera's own metres per pixel rather than asserted.
 *
 * **The bound.** These are properties of the generated bytes and of the chosen tile
 * size. They say nothing about how the tinted, lit, tone-mapped result looks: that is
 * the frame set's evidence, and no assertion here can stand in for it. The visibility
 * floors are derived from the renderer's own tone curve at the luminances the certified
 * frames show, so they predict a display-level change rather than measuring one.
 */
import { describe, expect, it } from "vitest";

import {
  createSurfaceDetailTexture,
  DETAIL_ANISOTROPY,
  DETAIL_SIZE,
  surfaceDetailBytes,
  SURFACE_DETAIL_METRES,
  SURFACE_DETAIL_STRENGTH,
  type SurfaceDetailKind,
} from "../src/scene/surface-detail.js";

const KINDS: readonly SurfaceDetailKind[] = ["ground", "road"];

/** Mean absolute difference between neighbouring texels, in 0-255 units. */
function adjacentDelta(texels: Uint8Array, step: number): number {
  let total = 0;
  let count = 0;
  for (let y = 0; y < DETAIL_SIZE; y += 1) {
    for (let x = 0; x < DETAIL_SIZE; x += 1) {
      const here = texels[(y * DETAIL_SIZE + x) * 4]!;
      const next = texels[(y * DETAIL_SIZE + ((x + step) % DETAIL_SIZE)) * 4]!;
      total += Math.abs(here - next);
      count += 1;
    }
  }
  return total / count;
}

describe("the surface detail tile is deterministic", () => {
  it("gives the same bytes for the same kind, every time", () => {
    for (const kind of KINDS) {
      const first = surfaceDetailBytes(kind);
      const second = surfaceDetailBytes(kind);
      expect(second.length).toBe(first.length);
      expect(Buffer.from(second).equals(Buffer.from(first))).toBe(true);
    }
  });

  it("gives the two surfaces different patterns", () => {
    const ground = surfaceDetailBytes("ground");
    const road = surfaceDetailBytes("road");
    expect(Buffer.from(road).equals(Buffer.from(ground))).toBe(false);
  });

  it("is opaque grey, one value per texel", () => {
    const texels = surfaceDetailBytes("ground");
    expect(texels.length).toBe(DETAIL_SIZE * DETAIL_SIZE * 4);
    for (let index = 0; index < texels.length; index += 4) {
      expect(texels[index]).toBe(texels[index + 1]);
      expect(texels[index]).toBe(texels[index + 2]);
      expect(texels[index + 3]).toBe(255);
    }
  });
});

describe("the tile carries structure at more than one scale", () => {
  it("is centred on the multiplier's neutral value", () => {
    for (const kind of KINDS) {
      const texels = surfaceDetailBytes(kind);
      let total = 0;
      let count = 0;
      for (let index = 0; index < texels.length; index += 4) {
        total += texels[index]!;
        count += 1;
      }
      // The shader reads `1 + (value/255 - 0.5) * strength`, so a mean away from the
      // midpoint would tint the surface rather than texture it. The generator centres
      // and scales the octave sum for exactly this, so the bound is tight.
      expect(Math.abs(total / count - 127.5)).toBeLessThan(1);
    }
  });

  it("has coarse variation, so minification does not converge it to flat", () => {
    for (const kind of KINDS) {
      const texels = surfaceDetailBytes(kind);
      // Mean of each 16x16 block: if the coarse octaves were missing, every block
      // would sit at the same value and this spread would collapse.
      const blocks: number[] = [];
      for (let by = 0; by < DETAIL_SIZE; by += 16) {
        for (let bx = 0; bx < DETAIL_SIZE; bx += 16) {
          let total = 0;
          for (let y = by; y < by + 16; y += 1) for (let x = bx; x < bx + 16; x += 1) total += texels[(y * DETAIL_SIZE + x) * 4]!;
          blocks.push(total / 256);
        }
      }
      const spread = Math.max(...blocks) - Math.min(...blocks);
      expect(spread, `${kind}: 16x16 block means span only ${spread.toFixed(1)} of 255`).toBeGreaterThan(20);
    }
  });

  it("wraps without a seam, so the tiling is not visible as a grid", () => {
    for (const kind of KINDS) {
      const texels = surfaceDetailBytes(kind);
      // The tile is periodic by construction, so the step across the wrap should look
      // like any other neighbouring step. A lattice that did not wrap would make this
      // roughly the difference between two unrelated texels instead.
      const interior = adjacentDelta(texels, 1);
      const wrap = adjacentDelta(texels, DETAIL_SIZE - 1);
      expect(wrap, `${kind}: wrap step ${wrap.toFixed(2)} against interior ${interior.toFixed(2)}`).toBeLessThan(interior * 2.5);
    }
  });
});

describe("the tile is chosen at a scale the far frames resolve", () => {
  it("spans several pixels at the overhead sweep's 1.374 m per pixel", () => {
    // 55 degrees vertical at 1280x720: the ground plane covers 2*d*tan(27.5) metres
    // vertically, so 1.374 m per pixel at the overhead shot's 950 m. A tile smaller
    // than a couple of pixels is minified to flat, which is the defect.
    const OVERHEAD_METRES_PER_PIXEL = (2 * 950 * Math.tan((27.5 * Math.PI) / 180)) / 720;
    expect(OVERHEAD_METRES_PER_PIXEL).toBeCloseTo(1.374, 2);
    for (const kind of KINDS) {
      expect(SURFACE_DETAIL_METRES[kind] / OVERHEAD_METRES_PER_PIXEL).toBeGreaterThan(2);
    }
    // And the road is the finer of the two, so the two surfaces are not the same
    // pattern at the same scale.
    expect(SURFACE_DETAIL_METRES.road).toBeLessThan(SURFACE_DETAIL_METRES.ground);
  });

  it("modulates the surface colour by a bounded fraction of its albedo", () => {
    for (const kind of KINDS) {
      // This bound used to be `< 0.35`, from "a strong multiplier would swing one of
      // them into mud or into blow-out". It was not the wrong instinct, but it was the
      // wrong bound: the strength is only half the modulation, and the shipped 0.16 was
      // invisible *because* the tile's local step was 2.3% of its own range. The case
      // below holds the product (step x strength) that a viewer actually sees, and this
      // one keeps the strength inside a range whose extremes stay plausible as surface
      // albedo: at 0.5 the tile swings a palette colour by ±25%.
      expect(SURFACE_DETAIL_STRENGTH[kind]).toBeGreaterThan(0.15);
      expect(SURFACE_DETAIL_STRENGTH[kind]).toBeLessThanOrEqual(0.5);
    }
  });
});

/**
 * The gate for the defect this tile exists to fix, and it is a gate on the product
 * rather than on the tile: what a viewer sees is the neighbouring-texel step *in
 * albedo*, which is the tile's step times the strength the shader applies.
 *
 * The measurement it replaces: the appearance batch landed at strength 0.16 with a
 * tile whose mip-0 mean neighbouring-texel step was 0.0226 of its range, giving
 * **0.36% of albedo on the road and 0.40% on the ground**. The 2026-09-18 re-inspection
 * of the frames captured after that landed measured exactly those figures and found
 * every ground and road crop unchanged from the pre-tile capture beyond dither — the
 * arithmetic was right and the contrast was two orders of magnitude short of a display
 * level. A relative albedo change of 1% buys about 0.36 of a 0-255 luminance level at
 * the luminances these surfaces occupy (ACES filmic at the style's exposure, then
 * sRGB), so under ~3% is sub-level and invisible.
 */
describe("the tile's neighbouring-texel step is visible, not merely present", () => {
  /** Mean and p95 of |difference| between horizontally adjacent texels, in -0.5..0.5. */
  function stepStats(texels: Uint8Array, size: number): { mean: number; p95: number } {
    const all: number[] = [];
    for (let y = 0; y < size; y += 1) {
      for (let x = 0; x < size - 1; x += 1) {
        all.push(Math.abs(texels[(y * size + x + 1) * 4]! - texels[(y * size + x) * 4]!) / 255);
      }
    }
    all.sort((a, b) => a - b);
    return {
      mean: all.reduce((sum, value) => sum + value, 0) / all.length,
      p95: all[Math.min(all.length - 1, Math.floor(all.length * 0.95))]!,
    };
  }

  /** What one mip level of box minification does, which is what distance selects. */
  function halve(texels: Uint8Array): Uint8Array {
    const next = new Uint8Array((DETAIL_SIZE / 2) * (DETAIL_SIZE / 2) * 4);
    for (let y = 0; y < DETAIL_SIZE / 2; y += 1) {
      for (let x = 0; x < DETAIL_SIZE / 2; x += 1) {
        let total = 0;
        for (let dy = 0; dy < 2; dy += 1) for (let dx = 0; dx < 2; dx += 1) total += texels[((2 * y + dy) * DETAIL_SIZE + 2 * x + dx) * 4]!;
        const grey = Math.round(total / 4);
        const at = (y * (DETAIL_SIZE / 2) + x) * 4;
        next[at] = grey;
        next[at + 1] = grey;
        next[at + 2] = grey;
        next[at + 3] = 255;
      }
    }
    return next;
  }

  it("puts at least 5% of albedo between neighbouring texels on the road", () => {
    // The road is the acceptance bar's material: "road asphalt shows structure at
    // hero-crossing distances (0.0144-0.0886 m/px)". At 0.0886 m/px the 4 m tile's
    // texels are 2.8 to a pixel, so the mip-0 step is the magnified end and the mip-1
    // step is the far end; both are asserted, because a tile that only survives
    // magnification would leave the road flat exactly where the finding was.
    const floors: Readonly<Record<SurfaceDetailKind, { at0: number; at1: number }>> = Object.freeze({
      road: Object.freeze({ at0: 0.045, at1: 0.025 }),
      ground: Object.freeze({ at0: 0.02, at1: 0.012 }),
    });
    for (const kind of KINDS) {
      const texels = surfaceDetailBytes(kind);
      const strength = SURFACE_DETAIL_STRENGTH[kind];
      const mip0 = stepStats(texels, DETAIL_SIZE);
      const mip1 = stepStats(halve(texels), DETAIL_SIZE / 2);
      const albedo0 = mip0.mean * strength;
      const albedo1 = mip1.mean * strength;
      expect(
        albedo0,
        `${kind}: mean neighbouring-texel step is ${(albedo0 * 100).toFixed(2)}% of albedo at mip 0 ` +
          `(p95 ${(mip0.p95 * strength * 100).toFixed(2)}%); the shipped-and-invisible tile measured 0.36% ` +
          `on the road and 0.40% on the ground, and under about 3% is less than one display level`,
      ).toBeGreaterThanOrEqual(floors[kind].at0);
      expect(
        albedo1,
        `${kind}: one mip level down the mean step is ${(albedo1 * 100).toFixed(2)}% of albedo, so the ` +
          "far end of the hero crossing's 0.0144-0.0886 m/px would be flat again",
      ).toBeGreaterThanOrEqual(floors[kind].at1);
      // The local step is a large fraction of the tile's range, not a rounding error on
      // a smooth hill: the shipped tile's was 2.3% of its range at mip 0.
      expect(mip0.mean / (mip0.p95 + mip0.mean), `${kind}: the field is still a smooth hill`).toBeGreaterThan(0.2);
    }
  });

  it("keeps the tile's coarse half, so minification does not converge it to flat", () => {
    // Down four mip levels the field must still vary between blocks: a pure white-noise
    // tile would average to its own mean and the overhead framing would go flat, which
    // is the failure the previous smooth tile was written to avoid.
    for (const kind of KINDS) {
      let level = surfaceDetailBytes(kind);
      for (let mip = 0; mip < 4; mip += 1) level = halve(level);
      const size = DETAIL_SIZE / 16;
      let sum = 0;
      for (let index = 0; index < size * size; index += 1) sum += level[index * 4]!;
      const mean = sum / (size * size);
      let sumSquares = 0;
      for (let index = 0; index < size * size; index += 1) sumSquares += (level[index * 4]! - mean) ** 2;
      const deviation = Math.sqrt(sumSquares / (size * size));
      expect(deviation, `${kind}: mip 4 has a standard deviation of only ${deviation.toFixed(2)} of 255`).toBeGreaterThan(3);
    }
  });
});

describe("the texture is set up for world-space tiling", () => {
  it("repeats, and generates mipmaps for the distance fade", () => {
    for (const kind of KINDS) {
      const texture = createSurfaceDetailTexture(kind);
      // Repeat wrapping is what makes a world-space coordinate a tile UV, and the mip
      // chain is the whole distance fade: `DataTexture` arrives with mipmaps off and
      // nearest filtering, so both are set explicitly and asserted here.
      expect(texture.wrapS).toBe(1000);
      expect(texture.wrapT).toBe(1000);
      expect(texture.generateMipmaps).toBe(true);
      // Grazing angles are how both of these surfaces are mostly seen, and an isotropic
      // footprint is chosen from the steeper derivative alone: without anisotropy the
      // mip level averages the grain away along the view direction too.
      expect(texture.anisotropy).toBe(DETAIL_ANISOTROPY);
      expect(texture.anisotropy).toBeGreaterThan(1);
      expect(texture.image.width).toBe(DETAIL_SIZE);
      expect(texture.image.height).toBe(DETAIL_SIZE);
      texture.dispose();
    }
  });
});
